# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/TouchOSCLayoutManagerWindow.ui'
#
# Created: Wed Nov  2 17:42:22 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.7
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layout_list_layout = QtGui.QHBoxLayout()
        self.layout_list_layout.setObjectName("layout_list_layout")
        self.src_layouts_layout = QtGui.QVBoxLayout()
        self.src_layouts_layout.setObjectName("src_layouts_layout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.src_layouts_layout.addWidget(self.label)
        self.src_layout_tree = QtGui.QTreeWidget(self.centralwidget)
        self.src_layout_tree.setObjectName("src_layout_tree")
        self.src_layout_tree.headerItem().setText(0, "1")
        self.src_layouts_layout.addWidget(self.src_layout_tree)
        self.src_buttons_layout = QtGui.QHBoxLayout()
        self.src_buttons_layout.setObjectName("src_buttons_layout")
        self.open_layout_button = QtGui.QPushButton(self.centralwidget)
        self.open_layout_button.setObjectName("open_layout_button")
        self.src_buttons_layout.addWidget(self.open_layout_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.src_buttons_layout.addItem(spacerItem)
        self.add_to_layout_button = QtGui.QPushButton(self.centralwidget)
        self.add_to_layout_button.setObjectName("add_to_layout_button")
        self.src_buttons_layout.addWidget(self.add_to_layout_button)
        self.src_layouts_layout.addLayout(self.src_buttons_layout)
        self.layout_list_layout.addLayout(self.src_layouts_layout)
        self.dest_layout_layout = QtGui.QVBoxLayout()
        self.dest_layout_layout.setObjectName("dest_layout_layout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.dest_layout_layout.addWidget(self.label_2)
        self.dest_layout_list = QtGui.QListWidget(self.centralwidget)
        self.dest_layout_list.setObjectName("dest_layout_list")
        self.dest_layout_layout.addWidget(self.dest_layout_list)
        self.dest_button_layout = QtGui.QHBoxLayout()
        self.dest_button_layout.setObjectName("dest_button_layout")
        self.new_layout_button = QtGui.QPushButton(self.centralwidget)
        self.new_layout_button.setObjectName("new_layout_button")
        self.dest_button_layout.addWidget(self.new_layout_button)
        self.open_button = QtGui.QPushButton(self.centralwidget)
        self.open_button.setObjectName("open_button")
        self.dest_button_layout.addWidget(self.open_button)
        self.save_button = QtGui.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.dest_button_layout.addWidget(self.save_button)
        self.save_as_button = QtGui.QPushButton(self.centralwidget)
        self.save_as_button.setObjectName("save_as_button")
        self.dest_button_layout.addWidget(self.save_as_button)
        self.dest_layout_layout.addLayout(self.dest_button_layout)
        self.layout_list_layout.addLayout(self.dest_layout_layout)
        self.verticalLayout_5.addLayout(self.layout_list_layout)
        self.layout_information_layout = QtGui.QHBoxLayout()
        self.layout_information_layout.setObjectName("layout_information_layout")
        self.layout_preview_gb = QtGui.QGroupBox(self.centralwidget)
        self.layout_preview_gb.setObjectName("layout_preview_gb")
        self.gridLayout = QtGui.QGridLayout(self.layout_preview_gb)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_preview_label = QtGui.QLabel(self.layout_preview_gb)
        self.layout_preview_label.setMinimumSize(QtCore.QSize(200, 200))
        self.layout_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_preview_label.setObjectName("layout_preview_label")
        self.gridLayout.addWidget(self.layout_preview_label, 0, 0, 1, 1)
        self.layout_information_layout.addWidget(self.layout_preview_gb)
        self.layout_info_gb = QtGui.QGroupBox(self.centralwidget)
        self.layout_info_gb.setObjectName("layout_info_gb")
        self.layout_information_layout.addWidget(self.layout_info_gb)
        self.verticalLayout_5.addLayout(self.layout_information_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tool_bar = QtGui.QToolBar(MainWindow)
        self.tool_bar.setObjectName("tool_bar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Source Layouts", None, QtGui.QApplication.UnicodeUTF8))
        self.open_layout_button.setText(QtGui.QApplication.translate("MainWindow", "Open Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.add_to_layout_button.setText(QtGui.QApplication.translate("MainWindow", "Add to Layout >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Destination Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.new_layout_button.setText(QtGui.QApplication.translate("MainWindow", "New Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.save_as_button.setText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.layout_preview_gb.setTitle(QtGui.QApplication.translate("MainWindow", "Layout Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.layout_preview_label.setText(QtGui.QApplication.translate("MainWindow", "No Preview Available", None, QtGui.QApplication.UnicodeUTF8))
        self.layout_info_gb.setTitle(QtGui.QApplication.translate("MainWindow", "Layout Information", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_bar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

